config/routes.rb
Orpheo::Application.routes.draw do
  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  authenticated :user do
    root :to => 'performers#index'
  end
  root :to => "performers#index"
  match "/pages/plans" => "pages#plans"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
  resources :performers
end

app/models/performer.rb
class Performer < ActiveRecord::Base
  attr_accessible :name, :description, :soundcloud_url
  validates_presence_of :name,
                    :description,
                    :user_id
  belongs_to :user, inverse_of: :performer
end

app/controllers/performers_controller.rb
class PerformersController < ApplicationController
  before_filter :authenticate_user!, :only => [:edit, :new, :create, :delete]

  def index
    @performers = Performer.all() rescue nil
  end

  def show
    @performer = Performer.find(params[:id]) 
  end

  def edit
    if user_signed_in?
      @performer = Performer.find_by_user_id(current_user.id)
    else
      flash[:notice] = "Please Sign In"
      redirect_to sign_in_path
    end
  end

  def new
    @performer = Performer.new
  end
  
  def create
    @performer = current_user.build_performer(params[:performer])
    @performer.user = current_user
    if @performer.save
      redirect_to @performer
    else 
      flash[:error] = "Unable to save band"
      redirect_to new_performer_path
    end
  end
end

app/helpers/performers_helper.rb
module PerformersHelper
end

app/views/performers/edit.html.erb
<h2>Edit Listing</h2>
<h4><%= @performer.name %></h4>
<%= form_for :performer do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <%= f.label :description, "Description" %>
  <%= f.text_field :description %>
<% end %>

app/views/performers/index.html.erb
<h2 class="text-center">Performers Around You</h2>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
  <td>Name</td>
  <td>Description</td>
  <td>View</td>
</tr>
</thead>
<tbody>
<% @performers.try :each do |performer| %>
  <tr>
    <td><%= performer.name %></td>
    <td><%= performer.description %></td>
    <td><%= link_to "View Listing", performer_path(performer) %></td>
  </tr>
<% end -%>
<tbody>
</table>

app/views/performers/new.html.erb
<%= form_for @performer, url: { action: "create" } do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :soundcloud_url %>
    <%= f.text_field :soundcloud_url %>
  </div>
  <div class="actions">
    <%= f.submit :List %>
  </div>
<% end %>

app/views/performers/show.html.erb
<h3 class="text-center"><%= @performer.name %></h3>
<p class="text-center"><%= @performer.description %></p>
<a href=<%= @performer.soundcloud_url %>>Listen to them now</a>